### PR TITLE
Force SymTridiagonal to have consistent lengths

### LINKED ISSUE #629: Tridiagonal errors on inconsistent lengths, but SymTriagonal doesn't
Compare:

```julia
julia> SymTridiagonal([1,2], [3,4])
2×2 SymTridiagonal{Int64,Array{Int64,1}}:
 1  3
 3  2
```

where the extra entries in the lower diagonal are ignored, to

```julia
julia> Tridiagonal([1,2], [3,4], [1,2])
ERROR: ArgumentError: cannot construct Tridiagonal from incompatible lengths of subdiagonal, diagonal and superdiagonal: (2, 2, 2)
Stacktrace:
 [1] Type at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/tridiag.jl:384 [inlined]
 [2] Tridiagonal(::Array{Int64,1}, ::Array{Int64,1}, ::Array{Int64,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/tridiag.jl:423
 [3] top-level scope at none:0
```

Seems inconsistent to me. Either both of them error, or both of them ignore extra elements in the lower/upper diagonals.

### PR DESCRIPTION
**Pull request by musoke**
https://github.com/JuliaLang/LinearAlgebra.jl/issues/629 pointed out that is possible to initialise SymTridiagonal with subdiagonal of length equal to the diagonal. This is inconsistent with Tridiagonal and Bidiagonal.

Check the lengths and error if the subdiagonal's length is not 1 less than the diagonal's length.

Remove tests for SymTridiagonal with length(ev) == length(dv).

Todo: 
- [x] add test that `len(dv) == len(ev)` now errors
- [x] remove tests with `len(dv)==len(ev)`
- [x] fix kron
- [x] @andreasnoack mentioned that changes may be need in the wrapper for [dstemr](https://www.netlib.org/lapack/explore-html/d4/dec/group__stemr_ga71cbf49a0387762afa39582e6abbe466.html#ga71cbf49a0387762afa39582e6abbe466). 
I don't think that any changes are needed for dstemr. As far as I can tell from https://github.com/JuliaLang/LinearAlgebra.jl/issues/1491, `dstemr` is called via `dstgr!`. It already has checks in place for the lengths of `de` and `ev`:
https://github.com/JuliaLang/LinearAlgebra.jl/blob/17325b74ec807f5237228512db1131ddfe4048e3/src/lapack.jl#L4043-L4058

Possible followups:
- [x] simplify `_evview`, now that `ev` always has the same length.
- [x] remove most calls to `_evview`

### CODE REVIEW

File: src/diagonal.jl [hunk 1]
```diff
@@ -828,8 +828,12 @@ end
 
 function kron(A::Diagonal, B::SymTridiagonal)
     kdv = kron(A.diag, B.dv)
-    # We don't need to drop the last element
-    kev = kron(A.diag, _pushzero(_evview(B)))
+    kev_long = kron(A.diag, _pushzero(_evview(B)))
+
+    # We must drop the last element while preserving the type
+    kev = similar(kev_long, length(kev_long)-1);
+    @inbounds kev .= kev_long[begin:end-1]
```
Comment (musoke) [inline src/diagonal.jl]: Is there a more efficient way to do this?

**Comment by musoke** [comment]
I think this is ready for review. @andreasnoack, could you take a look?

File: src/diagonal.jl (hunk 1 above)
Comment (araujoms) [inline src/diagonal.jl]:
```suggestion
    kev = similar(kdv, length(kdv) - 1)
    z = zero(first(kdv))
    counter = 0
    @inbounds for i in firstindex(A.diag):lastindex(A.diag) - 1
        ai = A.diag[i]
        for bj in B.ev
            counter += 1
            kev[counter] = ai * bj
        end
        counter += 1
        kev[counter] = z
    end
    ai = last(A.diag)
    @inbounds for bj in B.ev
        counter += 1
        kev[counter] = ai * bj
    end
```

Comment (musoke) [reply src/diagonal.jl]: Thank you @araujoms!

Comment (araujoms) [reply src/diagonal.jl]: You're welcome.

**Comment by araujoms** [comment]
I don't think any changes are needed in the `stegr` wrapper. You should remove these lines, though, as they are no longer needed:
https://github.com/JuliaLang/LinearAlgebra.jl/blob/17325b74ec807f5237228512db1131ddfe4048e3/src/lapack.jl#L4052-L4054
https://github.com/JuliaLang/LinearAlgebra.jl/blob/17325b74ec807f5237228512db1131ddfe4048e3/src/lapack.jl#L4103-L4105

Also, I think you should remove all calls to `_evview`.

**Comment by musoke** [comment]
Will do.

I wasn't sure if removing those lines would break things outside this repo.

**Comment by araujoms** [comment]
These functions are neither `public` nor `export`ed, so anybody using them outside `LinearAlgebra` are on their own.

**Comment by musoke** [comment]
Done.

**Comment by araujoms** [comment]
`_diagview` and `_evview_transposed` are still needed because of JuliaLang/julia#55383

You should remove these lines, since your PR fixes #874 :https://github.com/JuliaLang/LinearAlgebra.jl/blob/17325b74ec807f5237228512db1131ddfe4048e3/src/special.jl#L29-L31

File: test/diagonal.jl [hunk 2]
```diff
@@ -1033,7 +1031,7 @@ end
     @test (T / D)::Tridiagonal{Float64} == T
     # matrix eltype case
     K = 5
-    for elty in (Float64, ComplexF32), overlength in (1, 0)
+    for elty in (Float64, ComplexF32), overlength in (1,)
         S = SymTridiagonal([rand(elty, 2, 2) for _ in 1:K], [rand(elty, 2, 2) for _ in 1:K-overlength])
```
Comment (araujoms) [inline test/diagonal.jl]: Please remove the `overlength`.

File: test/special.jl [hunk 3]
```diff
@@ -480,29 +480,6 @@ end
...
-    @test T + S ≈ Mt + Ms
-    @test S + Bu ≈ Ms + Mbu
-    @test Bu + S ≈ Mbu + Ms
-    @test S + Bl ≈ Ms + Mbl
-    @test Bl + S ≈ Mbl + Ms
-end
-
 @testset "Ensure Strided * (Sym)Tridiagonal is Dense" begin
     x = rand(3)
     y = rand(3)
```
Comment (araujoms) [inline test/special.jl]:
```suggestion
```
This vector becomes superfluous.

File: test/tridiag.jl [hunk 4]
```diff
@@ -696,15 +693,9 @@ end
...
+    A = SymTridiagonal(fill(1.0, 3), fill(-1.0, 2))
     F = eigen(A)
-    A2 = SymTridiagonal(fill(1.0, 3), fill(-1.0, 2))
-    F2 = eigen(A2)
-    test_approx_eq_modphase(F.vectors, F2.vectors)
-    @test F.values ≈ F2.values ≈ eigvals(A) ≈ eigvals(A2)
-    @test eigvecs(A) ≈ eigvecs(A2)
-    @test eigvecs(A, eigvals(A)[1:1]) ≈ eigvecs(A2, eigvals(A2)[1:1])
+    @test F.values ≈ eigvals(A)
 end
```
Comment (araujoms) [inline test/tridiag.jl]: This entire testset becomes redundant and should be removed.

Comment (musoke) [reply test/tridiag.jl]: Done - thanks!

**Review by araujoms — APPROVED** [review]

**Comment by araujoms** [comment]
Thanks for your contribution! I think it's good for merging, but I'll leave it open for a couple more days to see if anyone wants to comment.

**Comment by musoke** [comment]
Sounds good - thank you for your help!

**Review by dkarrasch — APPROVED** [review]
LGTM, nice work!

**Comment by musoke** [comment]
🎉
