### PR TITLE
Make matmul work with zero-less eltypes

### LINKED ISSUE #1486: `*` on matrices of custom number types used to work in Julia <=1.10 and does not anymore (now requires `zero` to be defined and maybe shouldn't)
The following (minimum definition of addition and multiplication of modular numbers) enabled to multiply matrices in Julia 1.0 to 1.10 (and probably before, I was not using Julia then)

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.9 (2025-03-10)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> struct Mod<:Number
         val::Int
         modulo::Int
         Mod(x::Int,y::Int)=new(x%y,y)
       end

julia> Base.:+(x::Mod, y::Mod)=Mod(x.val+y.val,x.modulo)

julia> Base.:*(x::Mod, y::Mod)=Mod(x.val*y.val,x.modulo)

julia> m=Mod.([4 5;5 4],20)
2×2 Matrix{Mod}:
 Mod(4, 20)  Mod(5, 20)
 Mod(5, 20)  Mod(4, 20)

julia> m*m
2×2 Matrix{Mod}:
 Mod(1, 20)  Mod(0, 20)
 Mod(0, 20)  Mod(1, 20)

```

but in julia 11 and 12 we get

```
julia> m*m
ERROR: MethodError: no method matching Mod(::Int64)
The type `Mod` exists, but no method is defined for this combination of argument types when trying to construct it.

Closest candidates are:
  Mod(::Int64, ::Int64)
   @ Main REPL[1]:4
  (::Type{T})(::T) where T<:Number
   @ Core boot.jl:965
  (::Type{T})(::Base.TwicePrecision) where T<:Number
   @ Base twiceprecision.jl:265
  ...

Stacktrace:
  [1] convert(::Type{Mod}, x::Int64)
    @ Base ./number.jl:7
  [2] zero(::Type{Mod})
    @ Base ./number.jl:314
  [3] _rmul_or_fill!
    @ ~/julia-1.12.1/share/julia/stdlib/v1.12/LinearAlgebra/src/generic.jl:169 [inlined]
  [4] _generic_matmatmul_nonadjtrans!
    @ ~/julia-1.12.1/share/julia/stdlib/v1.12/LinearAlgebra/src/matmul.jl:1031 [inlined]
  [5] __generic_matmatmul!
    @ ~/julia-1.12.1/share/julia/stdlib/v1.12/LinearAlgebra/src/matmul.jl:1027 [inlined]
  [6] _generic_matmatmul!(C::Matrix{Mod}, A::Matrix{Mod}, B::Matrix{Mod}, alpha::Bool, beta::Bool)
    @ LinearAlgebra ~/julia-1.12.1/share/julia/stdlib/v1.12/LinearAlgebra/src/matmul.jl:1021
  [7] generic_matmatmul!
    @ ~/julia-1.12.1/share/julia/stdlib/v1.12/LinearAlgebra/src/matmul.jl:1011 [inlined]
  [8] generic_matmatmul_wrapper!
    @ ~/julia-1.12.1/share/julia/stdlib/v1.12/LinearAlgebra/src/matmul.jl:343 [inlined]
  [9] _mul!
    @ ~/julia-1.12.1/share/julia/stdlib/v1.12/LinearAlgebra/src/matmul.jl:328 [inlined]
 [10] mul!
    @ ~/julia-1.12.1/share/julia/stdlib/v1.12/LinearAlgebra/src/matmul.jl:297 [inlined]
 [11] mul!
    @ ~/julia-1.12.1/share/julia/stdlib/v1.12/LinearAlgebra/src/matmul.jl:265 [inlined]
 [12] mul
    @ ~/julia-1.12.1/share/julia/stdlib/v1.12/LinearAlgebra/src/matmul.jl:118 [inlined]
 [13] *(A::Matrix{Mod}, B::Matrix{Mod})
    @ LinearAlgebra ~/julia-1.12.1/share/julia/stdlib/v1.12/LinearAlgebra/src/matmul.jl:114
 [14] top-level scope
    @ REPL[5]:1
```

The problem is the call `zero(Mod)`, which should not be necessary to multiply two matrices. We can define

`Base.zero(x::Mod)=Mod(0,x.modulo)`

but not `zero(Mod)` since the type `Mod` does not contain the information `modulo`. I find this a serious regression in the generality of Julia. In mathematics, there are lots of similar numbers where `zero(x)` makes sense but not `zero(typeof(x))`, and Julia handles recently worse and  worse this type of numbers (I found also that `LinearAlgebra.det_bareiss(m)`, which used to work, does not anymore).

I think it is would be worth taking a minimum of care writing generic code in Linear algebra so more of it works with such objects. For example, one could use instead of   `zero(eltype(m))` a function

`zeroentry(m)=isempty(m) ? zero(eltype(m)) : zero(first(m))`

which would limit the problem to empty matrices.

### PR DESCRIPTION
**Pull request by dkarrasch**
This allows generic matmul to work with types that don't have a defined `zero`, but for which `zero` is defined on values. This avoids some trivial multiplications, and therefore contains a speed-up in generic syrk. I'm not sure if I was seeing slight performance drops in very small matrix cases, but AFAICT these code branches are not affected by the changes.

Fixes #1486.

### CODE REVIEW

File: src/matmul.jl [hunk 1]
```diff
@@ -599,11 +599,21 @@ function generic_syrk!(C::StridedMatrix{T}, A::StridedVecOrMat{T}, conjugate::Bo
...
     end
 
-    _rmul_or_fill!(C, β)
+    if (!iszero(β) || isempty(A)) # return C*beta
+        _rmul_or_fill!(C, β)
+    else # iszero(β) && A and B are non-empty
+        a1 = firstindex(A, 1)
+        a2 = firstindex(A, 2)
+        for j in axes(C, 2), i in axes(C, 1)
+            z1 = zero(A[i, a2]*A[a1, j] + A[i, a2]*A[a1, j])
```
Comment (jishnub) [inline src/matmul.jl]: This may not matter very much, but `A[a1, j]` may be moved out of the inner loop, and we may avoid the duplicate multiplication in the zero as
```julia
AA_ij = A[i, a2]*A[a1, j]
zi = zero(AA_ij + AA_ij)
```
These may often be optimized away, but it's better to be sure.

**Review by jishnub — APPROVED** [review]

File: src/matmul.jl [hunk 2]
```diff
@@ -1132,8 +1142,18 @@ __generic_matmatmul!(C, A, B, alpha, beta, ::Val{true}) = _generic_matmatmul_non
...
-    _rmul_or_fill!(C, beta)
-    (iszero(alpha) || isempty(A) || isempty(B)) && return C
+    # _rmul_or_fill!(C, beta) spelled out more carefully to allow for zero-less eltypes
+    if (!iszero(beta) || isempty(A) || isempty(B)) # return C*beta
+        _rmul_or_fill!(C, beta)
+    else # iszero(beta) && A and B are non-empty
+        a1 = firstindex(A, 2)
+        b1 = firstindex(B, 1)
+        for j in axes(C, 2), i in axes(C, 1)
+            z1 = zero(A[i, a1]*B[b1, j] + A[i, a1]*B[b1, j])
```
Comment (jishnub) [inline src/matmul.jl]: A similar hoisting might be possible here as well.

File: src/matmul.jl [hunk 3]
```diff
@@ -1145,20 +1165,37 @@ function _generic_matmatmul_nonadjtrans!(C, A, B, alpha, beta)
...
 function _generic_matmatmul_adjtrans!(C, A, B, alpha, beta)
-    _rmul_or_fill!(C, beta)
-    (iszero(alpha) || isempty(A) || isempty(B)) && return C
+    if (!iszero(beta) || isempty(A) || isempty(B)) # return C*beta
+        _rmul_or_fill!(C, beta)
+    else # iszero(beta) && A and B are non-empty
+        a1 = firstindex(A, 2)
+        b1 = firstindex(B, 1)
+        for j in axes(C, 2), i in axes(C, 1)
+            z1 = zero(A[i, a1]*B[b1, j] + A[i, a1]*B[b1, j])
```
Comment (jishnub) [inline src/matmul.jl]: Hoisting here

**Comment by araujoms** [comment]
I'm confused. I thought you wanted multiplication of empty matrices to fail, but it is just return a zero matrix of the appropriate size?

**Comment by dkarrasch** [comment]
No, I didn't want it to fail. And it has been working at least since v1.0. The only issue is that for empty matrices and a return eltype that doesn't have a `zero` (only for given elements), we can't fill the returned array with zeros. That's the throwing test.

File: src/matmul.jl [hunk 4]
```diff
@@ -599,11 +599,34 @@ function generic_syrk!(C::StridedMatrix{T}, A::StridedVecOrMat{T}, conjugate::Bo
...
+    if (!iszero(β) || isempty(A)) # return C*beta
+        _rmul_or_fill!(C, β)
+    else # iszero(β) && A is non-empty
+        if aat
+            for j ∈ 1:m
+                A_1j = A[j,1]'
+                for i ∈ 1:j
+                    A_ij = A[i,1]*A_1j
+                    z1 = zero(A_ij + A_ij)
+                    C[i,j] = convert(promote_type(typeof(z1), eltype(C)), z1)
```
Comment (araujoms) [inline src/matmul.jl]: why is this necessary? can `C[i,j]` have any type other than `eltype(C)`?

Comment (dkarrasch) [reply src/matmul.jl]: This is copied from the "old" most generic matmul code, but since potential promotion to the eltype of `C` is included in the `setindex!` operation here, I guess/agree this could be simply reduced to

```suggestion
                    C[i,j] = zero(A_ij + A_ij)
```

Comment (araujoms) [reply src/matmul.jl]: I see. Since `generic_syrk` is only written for `<:Number` that is rather overkill. Can't the whole thing be simplified to `fill!(C, zero(abs2(A[1,1]))` then?

Comment (dkarrasch) [reply src/matmul.jl]: I'm not sure. In https://github.com/JuliaLang/LinearAlgebra.jl/issues/1486#issuecomment-3570783725, the author says that matrices can be filled with numbers with different moduli, so I think we should keep as much flexibility/genericity here... unless I'm missing something.

Comment (araujoms) [reply src/matmul.jl]: If you do this you won't be able to multiply them, though.

Comment (dkarrasch) [reply src/matmul.jl]: I wasn't sure either, but the author said different moduli are all over the place. I don't know myself (and don't have complicated usecases), I'm just concerned that this is the most generic version, and we should make sure it works under the most generic conditions. I wonder actually why we restricted this to `Number`s in the first place. Gotta find the original PR.

Comment (araujoms) [reply src/matmul.jl]: We restricted it to `Number` because the only point of this function is speed, there is already a generic fallback for arbitrary types. And it's simpler and faster if we restrict it to `Number`.

I think generic code is good as long as we have a concrete use case, otherwise it's the path to madness.

Comment (dkarrasch) [reply src/matmul.jl]: I went basically with your suggestion.

Comment (araujoms) [reply src/matmul.jl]: I appreciate that. Why didn't you use `fill!`, though?

Comment (dkarrasch) [reply src/matmul.jl]: Because we say that we only compute the upper triangle. Perhaps I could use `fill!(UpperTriangular(C), ...)`.

**Review by araujoms — APPROVED** [review]
