### PR TITLE
In-place multiplication of `Diagonal` with OffsetMatrix should throw

### LINKED ISSUE #1525: `rmul!` accepts `OffsetArray`s, and reads out of bounds
```julia
julia> using OffsetArrays, LinearAlgebra

julia> rmul!(OffsetArray([1 2; 3 4], 5, 6), Diagonal([7, 8]))  # should be an error
2×2 OffsetArray(::Matrix{Int64}, 6:7, 7:8) with eltype Int64 with indices 6:7×7:8:
 7021710134324764715   6945210754644233948
 2618386329264742529  -4556322564421083720

julia> OffsetArray([1 2; 3 4], 5, 6) * Diagonal([7, 8])
ERROR: ArgumentError: offset arrays are not supported but got an array with index other than 1
Stacktrace:
 [1] require_one_based_indexing
   @ ./abstractarray.jl:131 [inlined]
 [2] __muldiag!(out::Matrix{…}, A::OffsetMatrix{…}, D::Diagonal{…}, _add::LinearAlgebra.MulAddMul{…})
   @ LinearAlgebra ~/.julia/juliaup/julia-1.11.7+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/diagonal.jl:365
```

### PR DESCRIPTION
**Pull request by dkarrasch**
Fixes #1525.

### CODE REVIEW

**Review by mcabbott — APPROVED** [review]

File: test/diagonal.jl [hunk 1]
```diff
@@ -988,7 +988,9 @@ end
     D = Diagonal(1:4)
     A = OffsetArray(rand(4,4), 2, 2)
     @test_throws ArgumentError D * A
+    @test_throws ArgumentError rmul!(D, A)
```
Comment (dkarrasch) [inline test/diagonal.jl]:
```suggestion
    @test_throws ArgumentError lmul!(D, A)
```

File: test/diagonal.jl [hunk 2]
```diff
@@ -988,7 +988,9 @@ end
...
     @test_throws ArgumentError A * D
+    @test_throws ArgumentError lmul!(A, D)
```
Comment (dkarrasch) [inline test/diagonal.jl]:
```suggestion
    @test_throws ArgumentError rmul!(A, D)
```

File: src/diagonal.jl [hunk 3]
```diff
@@ -406,6 +408,8 @@ end
 
 function lmul!(D::Diagonal, B::AbstractVecOrMat)
     matmul_size_check(size(D), size(B))
+    axes(D.diag, 1) == axes(B, 1) ||
+        throw(ArgumentError(lazy"second axis of D, $(axes(D, 2)), does not match first axis of A, $(axes(A, 1))"))
```
Comment (dkarrasch) [inline src/diagonal.jl]:
```suggestion
        throw(ArgumentError(lazy"second axis of D, $(axes(D, 2)), does not match first axis of B, $(axes(B, 1))"))
```
