### PR TITLE
Fix GEMM dispatch for complex-real matmul

### LINKED ISSUE #1519: Poor performance for product Matrix{ComplexF64} with Matrix{Float64}
Hi all,

I observe puzzlingly low performance for matrix-matrix products between Matrix{ComplexF64} and Matrix{Float64}, but not between Matrix{Float64} and Matrix{ComplexF64} (or Float64 Float64 and ComplexF64 ComplexF64). Could somebody confirm that I am not doing anything stupid?

MWE
```julia
N=2000;
F1 = rand(Float64, N, N);
F2 = rand(Float64, N, N);
C1 = rand(Complex{Float64}, N, N);
C2 = rand(Complex{Float64}, N, N);
@time F1 * F2;
@time C1 * C2;
@time F1 * C2;
@time C2 * F1;
@time C1 * F2; # Just to be sure...
```
Which returns (even after several calls to warm up):
```
0.018942 seconds (3 allocations: 30.518 MiB)
0.054659 seconds (3 allocations: 61.035 MiB)
0.082185 seconds (12 allocations: 152.592 MiB)
17.355046 seconds (3 allocations: 61.039 MiB)
19.586621 seconds (3 allocations: 61.039 MiB)
```
This seems to be a regression in 1.12.2, 1.11 does not appear to suffer from the same issue. And the issue can be reproduced on at least 2 machines.
```julia
versioninfo()
Julia Version 1.12.2
Commit ca9b6662be4 (2025-11-20 16:25 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) Ultra 7 268V
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, arrowlake-s)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 8 virtual cores)
```

### PR DESCRIPTION
**Pull request by jishnub**
This should fix #1519. The issue on master is that we have specialized dispatches for arrays of the same eltype, and the complex-real matmul ends up in `generic_matmatmul!`. This adds an extra method to ensure that the complex-real case also reaches BLAS.

```julia
julia> A = ones(ComplexF64, 400, 400); B = ones(size(A)); C = similar(A);

julia> @btime mul!($C, $A, $B);
  57.043 ms (0 allocations: 0 bytes) # master
  1.608 ms (0 allocations: 0 bytes) # this PR
```

### CODE REVIEW

**Comment by dkarrasch** [comment]
Is this redirecting to the "reinterpret-trick"? Did that get lost over the more recent changes?

**Comment by adienes** [comment]
just for posterity if it happens to be useful, I had just bisected this to https://github.com/JuliaLang/julia/pull/55002

**Comment by jishnub** [comment]
@dkarrasch Exactly, this had regressed from the previous behavior.

**Comment by jishnub** [comment]
@adienes Thanks for the bisect! It appears that the fix required is a bit different. The method already existed, but the BLAS flag format had changed between releases and hadn't been updated.

File: src/matmul.jl [hunk 1]
```diff
@@ -658,13 +658,9 @@ Base.@constprop :aggressive generic_matmatmul!(C::StridedMatrix{T}, tA, tB, A::S
     generic_matmatmul!(C, tA, tB, A, B, _add.alpha, _add.beta)
 
 function generic_matmatmul_wrapper!(C::StridedVecOrMat{Complex{T}}, tA, tB, A::StridedVecOrMat{Complex{T}}, B::StridedVecOrMat{T},
-                    α::Number, β::Number, ::Val{true}) where {T<:BlasReal}
+                    α::Number, β::Number, ::Val{BlasFlag.GEMM}) where {T<:BlasReal}
     gemm_wrapper!(C, tA, tB, A, B, α, β)
 end
-Base.@constprop :aggressive function generic_matmatmul_wrapper!(C::StridedVecOrMat{Complex{T}}, tA, tB, A::StridedVecOrMat{Complex{T}}, B::StridedVecOrMat{T},
```
Comment (jishnub) [inline src/matmul.jl:664]: I don't think this method is ever taken. `BlasReal` matrices would always use `GEMM` as the flag, and `gemm_wrapper!` may delegate to `_generic_matmatmul!` if necessary.
