### PR TITLE
Fix unitful 3-arg `*`

### LINKED ISSUE #1291: Wrong `eltype` in 3-arg `*`
Here matrix-matrix-scalar multiplication seems to make incorrect assumptions about what number type scalar multiplication will return:
```julia
julia> import Unitful

julia> a = 2.0Unitful.cm
2.0 cm

julia> b = 0.1Unitful.cm
0.1 cm

julia> a * [a b; -b a] * [a b; -b a]  # avoids the fast path, as Number not assumed to commute
2×2 Matrix{Unitful.Quantity{Float64, 𝐋³, Unitful.FreeUnits{(cm³,), 𝐋³, nothing}}}:
  7.98 cm³  0.8 cm³
 -0.8 cm³   7.98 cm³

julia> [a b; -b a] * [a b; -b a] * a  # uses fast path mat_mat_scalar
ERROR: DimensionError: 8.0 cm³ and 0.0 cm are not dimensionally compatible.
Stacktrace:
  [1] _muladd
    @ ~/.julia/packages/Unitful/nwwOk/src/quantities.jl:197 [inlined]
  [2] muladd
    @ ~/.julia/packages/Unitful/nwwOk/src/quantities.jl:192 [inlined]
  [3] macro expansion
    @ ~/.julia/juliaup/julia-1.11.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/matmul.jl:897 [inlined]
  [4] macro expansion
    @ ./simdloop.jl:77 [inlined]
  [5] _generic_matmatmul!(C::Matrix{…}, A::Matrix{…}, B::Matrix{…}, _add::LinearAlgebra.MulAddMul{…})
    @ LinearAlgebra ~/.julia/juliaup/julia-1.11.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/matmul.jl:896
  [6] generic_matmatmul!
    @ ~/.julia/juliaup/julia-1.11.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/matmul.jl:868 [inlined]
  [7] _mul!
    @ ~/.julia/juliaup/julia-1.11.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/matmul.jl:287 [inlined]
  [8] mul!
    @ ~/.julia/juliaup/julia-1.11.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/matmul.jl:285 [inlined]
  [9] _mat_mat_scalar
    @ ~/.julia/juliaup/julia-1.11.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/matmul.jl:1167 [inlined]
 [10] mat_mat_scalar
    @ ~/.julia/juliaup/julia-1.11.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/matmul.jl:1161 [inlined]
 [11] *(A::Matrix{Unitful.Quantity{…}}, B::Matrix{Unitful.Quantity{…}}, γ::Unitful.Quantity{Float64, 𝐋, Unitful.FreeUnits{…}})
    @ LinearAlgebra ~/.julia/juliaup/julia-1.11.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/matmul.jl:1122
 [12] top-level scope
    @ REPL[419]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by dkarrasch**
Fixes #1291.

### CODE REVIEW

File: src/matmul.jl [hunk 1]
```diff
@@ -1444,7 +1445,7 @@ mat_mat_scalar(A::StridedMaybeAdjOrTransMat, B::StridedMaybeAdjOrTransMat, γ) =
     _mat_mat_scalar(A, B, γ)
 
 function _mat_mat_scalar(A, B, γ)
-    T = promote_type(eltype(A), eltype(B), typeof(γ))
+    T = promote_op(*, promote_op(matprod, eltype(A), eltype(B)), typeof(γ))
```
Comment (mcabbott) [inline src/matmul.jl:1448]: This looks good! Sorry I didn't get it right the first time...

File: src/matmul.jl [hunk 2]
```diff
@@ -1075,7 +1075,8 @@ function __generic_matvecmul!(::typeof(identity), C::AbstractVector, A::Abstract
             elseif length(B) == 0
                 C[i] = zero(eltype(C))
             else
-                C[i] = zero(A[i]*B[1] + A[i]*B[1])
+                ci   = @stable_muladdmul MulAddMul(alpha,false)(A[i]*B[1])
+                C[i] = zero(ci + ci)
```
Comment (mcabbott) [inline src/matmul.jl:1079]: I don't see why this is related. But it also looks fine, assuming `@stable_muladdmul MulAddMul` does something reasonable, and that tests pass.

File: src/matmul.jl [hunk 3]
```diff
@@ -1147,12 +1148,12 @@ function _generic_matmatmul_nonadjtrans!(C, A, B, alpha, beta)
...
             B_1j = B[b1, j]
             for i in axes(C, 1)
-                C_ij = A[i, a1] * B_1j
+                C_ij = @stable_muladdmul MulAddMul(alpha, false)(A[i, a1] * B_1j)
                 C[i,j] = zero(C_ij + C_ij)
             end
         end
     end
-    iszero(alpha) && return C
+    (iszero(alpha) || isempty(A) || isempty(B)) && return C
```
Comment (mcabbott) [inline src/matmul.jl:1156]: I don't see why this is related. Appears safe, given that we've already dealt with `beta!=0` above. 

But I'm confused about the case of nonzero beta and non-empty A,B in code just above. It seems that this code does `C .*= beta`, but then ignores A, B? Maybe I'm missing something. Not new to this PR. Haven't looked at tests for this.

**Review by mcabbott — APPROVED** [review]

File: src/matmul.jl (hunk 2 above)
Comment (dkarrasch) [reply src/matmul.jl:1079]: This is because C is the product of `A`, `B` and `alpha`, in your example each with unit, so `A*B` is to the power of 2, not to the power of 3. The `MulAddMul` stuff is just `A[i]*B[1]*alpha`, except when `isone(alpha)`, then the multiplication is skipped.

File: src/matmul.jl (hunk 3 above)
Comment (dkarrasch) [reply src/matmul.jl:1156]: Yes, in that part it does `C .*= beta`. If `iszero(alpha)`, then this is all that needs to be done in

```julia
C = A*B*alpha + C*beta
```

This change is unrelated, it just avoids "running empty loops" in the sequel.
