### PR TITLE
Specialize Diagonal * Adjoint

### LINKED ISSUE #1205: Performance regression for (*)(A, D::Diagonal) when A is the adjoint of a sparse matrix
Matrix-matrix multiplication with types `A <: Adjoint{T, SparseMatrixCSC{T, N}}` and `B <: Diagonal` is significantly slower in Julia 1.11 than in Julia 1.10. The MWE below executes in O(n) time with Julia 1.10, and in O(n<sup>2</sup>) time with Julia 1.11. 

The performance regression appears to have been introduced in PR https://github.com/JuliaLang/julia/pull/52389 that removed specialized methods.

### MWE

```
using LinearAlgebra
using SparseArrays
using BenchmarkTools

n = 100;
A = adjoint(sparse(Float64, I, n, n));
B = Diagonal(ones(n));

print("Julia ", VERSION, ", n = ", n, ":")
@btime *($A, $B)
```

Output:

```
Julia 1.10.8, n = 100:  531.160 ns (5 allocations: 2.59 KiB)
Julia 1.11.3, n = 100:  65.927 μs (10 allocations: 8.53 KiB)
```
```
Julia 1.10.8, n = 1000:  4.626 μs (5 allocations: 23.88 KiB)
Julia 1.11.3, n = 1000:  6.240 ms (13 allocations: 57.38 KiB)
```
```
Julia 1.10.8, n = 10000:  43.303 μs (6 allocations: 234.73 KiB)
Julia 1.11.3, n = 10000:  623.509 ms (13 allocations: 666.56 KiB)
```
```
Julia 1.10.8, n = 100000:  450.953 μs (6 allocations: 2.29 MiB)
Julia 1.11.3, n = 100000:  62.992 s (13 allocations: 5.01 MiB)
```

These results are on a Linux x86-64 platform; similar results were observed on MacOS x86-64.

### PR DESCRIPTION
**Pull request by jishnub**
This reinstates slightly altered versions of the methods that were removed in https://github.com/JuliaLang/julia/pull/52389. Sort of fixes #1205, although this doesn't recover the full performance. However, this version is more general, and works with the example presented in https://github.com/JuliaLang/julia/pull/52389. There's still a performance regression, but the full performance may only be obtained for mutable matrices, and we may not assume mutability in general.

Performance:
v1.10:

```julia
julia> n = 100
100

julia> A = adjoint(sparse(Float64, I, n, n));

julia> B = Diagonal(ones(n));

julia> @btime $A * $B;
  837.119 ns (5 allocations: 2.59 KiB)
```

This PR
```julia
julia> @btime $A * $B;
  1.106 μs (15 allocations: 5.56 KiB)
```
We need double the allocations here compared to earlier, as we firstly materialize `D' * A'`, and then we again copy the adjoint of this result. I wonder if this may be reduced.

### CODE REVIEW

File: src/diagonal.jl [hunk 1]
```diff
@@ -332,6 +332,15 @@ function (*)(D::Diagonal, V::AbstractVector)
     return D.diag .* V
 end
 
+function (*)(A::AdjOrTransAbsMat, D::Diagonal)
+    adj = wrapperop(A)
+    copy(adj(adj(D) * adj(A)))
```
Comment (stevengj) [inline src/diagonal.jl:335]: It doesn't look like we have any optimized methods for `adjoint(diagonal) * matrix`, or am I missing something?

Comment (jishnub) [reply src/diagonal.jl:335]: `adjoint` of a `Diagonal` produces a `Diagonal`, so it's still a `Diagonal` times a matrix.

https://github.com/JuliaLang/LinearAlgebra.jl/blob/ed35a377cd3945c91654cabc0bac9cbed2d67a0e/src/diagonal.jl#L830-L832

**Comment by dkarrasch** [comment]
Should we add methods for strided `AdjOrTrans` for even better performance? But that doesn't guarantee mutability of individual entries, right? Otherwise, looks good to go.

**Comment by jishnub** [comment]
We may add these methods, but non-strided mutable matrices (such as `SparseArray`s) will still be slow. Perhaps we need a mutability trait, like `ArrayInterface`.

**Comment by dkarrasch** [comment]
> `SparseArray`s) will still be slow

We could take care of that case specifically over there. But performance is not too bad for that case, as you showed.

**Review by dkarrasch — APPROVED** [review]
LGTM. Could you perhaps take a look at SparseArrays.jl to see what it needs there to bring back the inplace multiplication?

**Comment by jishnub** [comment]
For the future: if https://github.com/JuliaLang/LinearAlgebra.jl/pull/1210 is merged, we may specialize `mul` directly, instead of redirecting `*` to `_diag_adj_mul`.

**Comment by dkarrasch** [comment]
> For the future: if #1210 is merged, we may specialize `mul` directly, instead of redirecting `*` to `_diag_adj_mul`.

I'd suggest we do that: having only generic `*` methods, and everything else (like bidiag*hessenberg, and whatnot) should be dispatched through `mul`.

**Comment by dkarrasch** [comment]
I forgot: if we want to backport, we can't use the new stuff. So `mul` has to go into a new PR.
