### PR TITLE
make checksquare fail on non-matrices

### LINKED ISSUE #1362: checksquare should error for generic arrays
Currently

1. it works for more than two dimensions,
2. regardless of what the trailing sizes are

```julia
julia> LinearAlgebra.checksquare(zeros(1,1,1))
1

julia> LinearAlgebra.checksquare(zeros(1,1,2))
1
```

Incidentally, the docstring should document that the error thrown is a `DimensionError`.

### PR DESCRIPTION
**Pull request by araujoms**
Closes #1362

### CODE REVIEW

**Review by stevengj — APPROVED** [review]

File: src/LinearAlgebra.jl [hunk 1]
```diff
@@ -340,16 +340,16 @@ julia> LinearAlgebra.checksquare(A, B)
...
-    m,n = size(A)
-    m == n || throw(DimensionMismatch(lazy"matrix is not square: dimensions are $(size(A))"))
-    m
+    sizeA = size(A)
+    length(sizeA) == 2 || throw(DimensionMismatch(lazy"input is not a matrix: dimensions are $sizeA"))
+    sizeA[1] == sizeA[2] || throw(DimensionMismatch(lazy"matrix is not square: dimensions are $sizeA"))
+    return sizeA[1]
 end
 
 function checksquare(A...)
```
Comment (stevengj) [inline src/LinearAlgebra.jl]: Side note: it seems pretty weird and sub-optimal that this function returns a vector and not a tuple.

i.e. it seems like it should really be:
```jl
checksquare(A...) = map(checksquare, A) # returns a tuple
```
but since it is public and documented maybe it can't be fixed?

That being said, a simpler implementation returning a vector would be
```jl
checksquare(A...) = Int[checksquare(a) for a in A]
```

Comment (araujoms) [reply src/LinearAlgebra.jl]: I agree. Personally I'm rather blasé about changing the return type of functions, but I'm afraid @jishnub would object. In any case, thanks for the one liner, I don't see how could I have missed it.

Comment (dkarrasch) [reply src/LinearAlgebra.jl]: The tuple-vs-vector issue related to `checksquare` has been discussed many times, and it was common sense that we can't change it. We might introduce an internal function, though, that returns tuples and use it inside LinearAlgebra.jl.

**Review by jishnub — APPROVED** [review]
